version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: momo-store-backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: momo-store-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VUE_APP_API_URL=http://89.169.156.255:8081
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge