name: Docker Project Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push_to_docker_hub:
      name: Push Docker image to DockerHub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker 
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Push Backend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/docker-project-backend:latest
        - name: Push Frontend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./frontend/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest

  trivy_scan:
    name: Security scan with Trivy
    runs-on: ubuntu-latest
    needs: [build_and_push_to_docker_hub]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Scan backend image (HIGH,CRITICAL)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ secrets.DOCKER_USER }}/docker-project-backend:latest
          format: 'table'
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '1'

      - name: Scan frontend image (HIGH,CRITICAL)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest
          format: 'table'
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '1'

      - name: Scan repository filesystem (configs & deps)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          security-checks: 'vuln,config,secret'
          exit-code: '0'

  run-with-docker-compose:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build via Docker Compose
        uses: hoverkraft-tech/compose-action@v2.2.0

  deploy_to_server:
    name: Deploy to 89.169.156.255
    runs-on: ubuntu-latest
    needs: [build_and_push_to_docker_hub]
    steps:
      - name: Deploy over SSH and run containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 89.169.156.255
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USER }}/docker-project-backend:latest
            docker pull ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest
            
            # Останавливаем системный nginx если он запущен
            sudo systemctl stop nginx || true
            
            # Останавливаем и удаляем все старые контейнеры
            docker stop $(docker ps -q) || true
            docker rm -f $(docker ps -aq) || true
            
            # Удаляем старую сеть и создаем новую
            docker network rm app-network || true
            docker network create app-network
            
            # Запускаем 2 экземпляра бэкенда (без публикации портов)
            docker run -d \
              --name backend-1 \
              --restart unless-stopped \
              --network app-network \
              -e PORT=8081 \
              ${{ secrets.DOCKER_USER }}/docker-project-backend:latest
            docker run -d \
              --name backend-2 \
              --restart unless-stopped \
              --network app-network \
              -e PORT=8081 \
              ${{ secrets.DOCKER_USER }}/docker-project-backend:latest

            # Фронтенд (ходит на /api)
            docker run -d \
              --name frontend \
              --restart unless-stopped \
              --network app-network \
              ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest

            # Подтянуть актуальный nginx.conf и запустить балансировщик на 80
            rm -f nginx.conf || true
            wget -O nginx.conf https://raw.githubusercontent.com/${{ github.repository }}/main/nginx.conf
            docker run -d \
              --name nginx \
              --restart unless-stopped \
              --network app-network \
              -p 80:80 \
              -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf:ro \
              nginx:alpine